import { Folder, TabsData } from '@/types/common';

export const defaultTabs: TabsData[] = [
  {
    active: true,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://www.baidu.com/favicon.ico',
    groupId: -1,
    height: 788,
    highlighted: true,
    id: '0caed8ed-2aa2-4e79-b36c-63fe58c8ed93',
    incognito: false,
    index: 15,
    mutedInfo: { muted: false },
    pinned: false,
    selected: true,
    status: 'complete',
    title: '百度一下，你就知道',
    url: 'https://www.baidu.com/',
    width: 1440,
    windowId: 947277100,
  },
  {
    active: true,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://www.google.com/favicon.ico',
    groupId: -1,
    height: 788,
    highlighted: true,
    id: '281c9954-35f7-4497-ac6c-9072952e1ada',
    incognito: false,
    index: 15,
    mutedInfo: { muted: false },
    openerTabId: 947279131,
    pinned: false,
    selected: true,
    status: 'loading',
    title: 'Google',
    url: 'https://www.google.com/',
    width: 1440,
    windowId: 947277100,
  },
  {
    active: true,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://cn.vuejs.org/logo.svg',
    groupId: -1,
    height: 788,
    highlighted: true,
    id: 'b06bcbbe-f7d3-4cfe-ad27-503b228b52f8',
    incognito: false,
    index: 11,
    mutedInfo: { muted: false },
    pinned: false,
    selected: true,
    status: 'complete',
    title: 'Vue.js - 渐进式 JavaScript 框架 | Vue.js',
    url: 'https://cn.vuejs.org/',
    width: 1440,
    windowId: 947277100,
  },
  {
    active: true,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://react.docschina.org/favicon.ico',
    groupId: -1,
    height: 788,
    highlighted: true,
    id: 'b4343d1c-cf47-4233-8fe2-96044d1e022b',
    incognito: false,
    index: 13,
    mutedInfo: { muted: false },
    openerTabId: 947279131,
    pinned: false,
    selected: true,
    status: 'loading',
    title: 'React 官方中文文档 – 用于构建用户界面的 JavaScript 库',
    url: 'https://react.docschina.org/',
    width: 1440,
    windowId: 947277100,
  },
  {
    active: true,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl: 'https://www.36kr.com/favicon.ico',
    groupId: -1,
    height: 788,
    highlighted: true,
    id: '0cee58da-6a57-40ac-8bb2-1748c68c85f6',
    incognito: false,
    index: 13,
    mutedInfo: { muted: false },
    openerTabId: 947279131,
    pinned: false,
    selected: true,
    status: 'loading',
    title: '36氪_让一部分人先看到未来',
    url: 'https://www.36kr.com/',
    width: 1440,
    windowId: 947277100,
  },
  {
    active: true,
    audible: false,
    autoDiscardable: true,
    discarded: false,
    favIconUrl:
      'https://lf3-cdn-tos.bytescm.com/obj/static/xitu_juejin_web//static/favicons/favicon-32x32.png',
    groupId: -1,
    height: 788,
    highlighted: true,
    id: 'ee5a9684-224e-4eba-a93b-0f62058bf122',
    incognito: false,
    index: 15,
    mutedInfo: { muted: false },
    openerTabId: 947279131,
    pinned: false,
    selected: true,
    status: 'loading',
    title: '稀土掘金',
    url: 'https://juejin.cn/',
    width: 1440,
    windowId: 947277100,
  },
];

export const defaultData: Folder[] = [
  {
    id: '001',
    name: '默认书签',
    list: [...defaultTabs],
    // type: 'folder',
  },
];
